#ifndef COLOURCODING_GENERATEMANUAL_H_INCLUDED
#define COLOURCODING_GENERATEMANUAL_H_INCLUDED

extern void ColourCoding_GenerateRefernceManual(void);

#endif // COLOURCODING_GENERATEMANUAL_H_INCLUDED
